### ISSUE TITLE
炭酸飲料の判別

### ISSUE THREAD

**Issue by kobarius** [kobarius/DJglass#1]
どうやってセンシングするか？
CO2は無理？
音（シュワシュワ）や画像（泡）では？

**Comment by kobarius** [comment]
言ったわね(￣ー￣)ﾆﾔﾘ

**Comment by dashimaki360** [comment]
グラスの上から撮影した画像があれば
- ドリンクの量
- 色
- 炭酸の量
- ドリンクの種類の推定
など多分分かると思う
温度は推定するの難しいかなあ

条件がいいと簡単で精度もよくなる
- グラスの種類固定
- グラスとカメラの位置関係固定
- 照明の影響が少ない

音を変えるだけなら
そもそも精度はいらないような気もするが

**Comment by dashimaki360** [comment]
実験結果
ドリンクの識別  可能
泡の測定     困難
氷の量測定  困難
